### ISSUE TITLE
Overlapping does not work with medium-large text

### ISSUE THREAD

**Issue by asevillano** [gioelecrispo/chunkipy#3]
Hi,

I have tested it with Bert token estimator and with tiktoken token calculation and the results are a bit different (because the number of tokens are a bit different) but at the end the problem is the same, the chunks generated are not overlapping between them.

this is the class and the method with bert:
**_class BertTokenEstimator(TokenEstimator):
    def __init__(self):
        self.bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
    def estimate_tokens(self, text):
        return len(self.bert_tokenizer.encode(text))

bert_token_estimator = BertTokenEstimator()
bert_text_chunker = TextChunker(512, tokens=True, overlap_percent=0.25, token_estimator=BertTokenEstimator())

def bert_get_chunks(text):
    # Generate chunks with overlapping
    chunks = bert_text_chunker.chunk(text)
    return chunks_**

and this is the text (it is in markdown format but any way in plain text is also happening), the function call and the results:
text = """
Descripción: Ayuda Elypse
===
||
| - |
| Apartados que cambian Descripci?³n del cambio Fecha entrada en vigor Fecha actualización del documento Lanzamiento promoci?³n 23/06/2020 24/06/2020 |
| |
| 1 1 ¿En qué consiste la promoción? |
| |
| La Liga y Mediapro han llegado a un acuerdo con los operadores para que puedan ofrecer el f??tbol gratis (Canal La Liga TV) en las residencias de ancianos Telef?³nica participa de este acuerdo dando a las residencias un producto con los mismos contenidos que el de BAR pero a un precio mucho m??s competitivo Al cliente le hablamos de un producto para residencias a un precio muy competitivo yÂ con el canal LaLiga TV gratis, no de una promoci?³n sobre el producto BAR A qui??n aplica: Residencias de ancianos (incluidas en el c?³didgo CNAE 8731 -asistencia en establecimientos residenciales para personas mayores-) que llamen para solicitar el f??tbol gratuito en sus residencias (zonas comunes y cafeter?­a) Tambi??n para residencias que tengan el producto BAR instalado en la cafeter?­a o zona com??n y soliciten el f??tbol gratis Cuando llame al 1004 o acuda a una tienda el responsable de una residencia de ancianos para solicitar el producto, derivar siempre la demanda a su comercial o al 900 26 22 62 El PVP del producto es de 112 â??/mes IVA incluido (pese a que el f??tbol -LIGA TV- es gratis, el producto tiene otros contenidos que s?­ tienen un coste) hasta el 31 de agosto de 2020 |
| |
| Asegura siempre |
| |
| Informa al cliente de que esta promoci?³n ser?? v??lida solo para residencias de ancianos; aquellas incluidas en el c?³digo CNAE 8731 Se har??n comprobaciones antes y despu??s de instalar el equipo |
| |
| Contratación y disfrute |
| |
| Fechas de contratación Fechas o periodo de disfrute Desde 23/06/2020 Hasta 31/08/2020 Hasta el 31 de agosto |
| |
| |
| 1 2 ¿A quién va dirigida? |
| |
| Residencias de ancianos Solo disponible en tecnolog?­a 1P SAT Segmento del cliente: Autónomos Empresas |
| |
| |
| 1 3 Incompatibilidades |
| |
| No aplica |
| |
| |
| 1 4 Canales de Venta |
| |
| Otros Instaladores DTS y Digitex |
| |
| |
| 1 5 Comunicación |
| |
| Campañas en Medios Otros soportes de comunicación N/A N/A |
| |
| |
| 1 6 Mantenimiento de la promoción |
| |
| No aplica |
| |
| |
| 1 7 Compromiso de la promoci?³n y movimientos con penalizaci?³n |
| |
| No aplica |
| |
| |
| 1 8 Hitos de la promoción (detallados) |
| |
| Fecha Descripción 23/06/2020 Lanzamiento promoci?³n Residencias de ancianos 112 â??/mes hasta el 31 de agosto de 2020 |
| |
. 
Argumentación: Ayuda Elypse
===
# 2 Argumentaci?³n
||
| - |
| CLAIM COMERCIAL: Para clientes que soliciten el nuevo producto para residencias de ancianos Movistar es consciente de la situaci?³n que se ha generando y lo impactadas que se han visto las residencias de ancianos Por eso quiere ofrecer un producto de difusi?³n p??blica con las mejores condiciones posibles Para que nuestros mayores puedan disfrutar del f??tbol |
| |
. 
Precios y Factura: ERROR DOC INTEL. 
Tramitación: Ayuda Elypse
===
# 4 Tramitaci?³n

4 1 Tramitaci?³n TELCO
No aplica, ya que estos productos no est??n disponibles en Telco

4 2 Tramitaci?³n no TELCO
No aplica
"""

_**print(f"Num of chars: {len(text)}")
print(f"Num of tokens (using bert): {bert_token_estimator.estimate_tokens(text)}")
chunks = bert_get_chunks(text)
i=1
for chunk in chunks:
    print(f'[{i}]: tokens: {bert_token_estimator.estimate_tokens(chunk)},\nchunk: [{chunk}]')
    print('------------------------')
    i+=1
print(f'total number of chunks: {i-1}')**_

this is the results:

Num of chars: 3171
Num of tokens (using bert): 1138

[1]: tokens: 107,
chunk: [['Descripción: Ayuda Elypse\n===\n||\n| - |\n| Apartados que cambian Descripci?³n del cambio Fecha entrada en vigor Fecha actualización del documento Lanzamiento promoci?³n 23/06/2020 24/06/2020 |\n| |\n| 1 1 ¿En qué consiste la promoción? |\n| |\n|]
------------------------
[2]: tokens: 567,
chunk: [['Descripción: Ayuda Elypse\n===\n||\n| - |\n| Apartados que cambian Descripci?³n del cambio Fecha entrada en vigor Fecha actualización del documento Lanzamiento promoci?³n 23/06/2020 24/06/2020 |\n| |\n| 1 1 ¿En qué consiste la promoción? |\n| |\n| La Liga y Mediapro han llegado a un acuerdo con los operadores para que puedan ofrecer el f??tbol gratis (Canal La Liga TV) en las residencias de ancianos Telef?³nica participa de este acuerdo dando a las residencias un producto con los mismos contenidos que el de BAR pero a un precio mucho m??s competitivo Al cliente le hablamos de un producto para residencias a un precio muy competitivo yÂ con el canal LaLiga TV gratis, no de una promoci?³n sobre el producto BAR A qui??n aplica: Residencias de ancianos (incluidas en el c?³didgo CNAE 8731 -asistencia en establecimientos residenciales para personas mayores-) que llamen para solicitar el f??tbol gratuito en sus residencias (zonas comunes y cafeter?a) Tambi??n para residencias que tengan el producto BAR instalado en la cafeter?a o zona com??n y soliciten el f??tbol gratis Cuando llame al 1004 o acuda a una tienda el responsable de una residencia de ancianos para solicitar el producto, derivar siempre la demanda a su comercial o al 900 26 22 62 El PVP del producto es de 112 â??/mes IVA incluido (pese a que el f??tbol -LIGA TV- es gratis, el producto tiene otros contenidos que s? tienen un coste) hasta el 31 de agosto de 2020 |\n| |\n| Asegura siempre |\n| |\n| Informa al cliente de que esta promoci?³n ser?? v??lida solo para residencias de ancianos;]
------------------------
[3]: tokens: 371,
chunk: [aquellas incluidas en el c?³digo CNAE 8731 Se har??n comprobaciones antes y despu??s de instalar el equipo |\n| |\n| Contratación y disfrute |\n| |\n| Fechas de contratación Fechas o periodo de disfrute Desde 23/06/2020 Hasta 31/08/2020 Hasta el 31 de agosto |\n| |\n| |\n| 1 2 ¿A quién va dirigida? |\n| |\n| Residencias de ancianos Solo disponible en tecnolog?a 1P SAT Segmento del cliente: Autónomos Empresas |\n| |\n| |\n| 1 3 Incompatibilidades |\n| |\n| No aplica |\n| |\n| |\n| 1 4 Canales de Venta |\n| |\n| Otros Instaladores DTS y Digitex |\n| |\n| |\n| 1 5 Comunicación |\n| |\n| Campañas en Medios Otros soportes de comunicación N/A N/A |\n| |\n| |\n| 1 6 Mantenimiento de la promoción |\n| |\n| No aplica |\n| |\n| |\n| 1 7 Compromiso de la promoci?³n y movimientos con penalizaci?³n |\n| |\n|]
------------------------
[4]: tokens: 397,
chunk: [No aplica |\n| |\n| |\n| 1 7 Compromiso de la promoci?³n y movimientos con penalizaci?³n |\n| |\n| No aplica |\n| |\n| |\n| 1 8 Hitos de la promoción (detallados) |\n| |\n| Fecha Descripción 23/06/2020 Lanzamiento promoci?³n Residencias de ancianos 112 â??/mes hasta el 31 de agosto de 2020 |\n| |\n.\nArgumentación: Ayuda Elypse\n===', '# 2 Argumentaci?³n\n||\n| - |\n| CLAIM COMERCIAL: Para clientes que soliciten el nuevo producto para residencias de ancianos Movistar es consciente de la situaci?³n que se ha generando y lo impactadas que se han visto las residencias de ancianos Por eso quiere ofrecer un producto de difusi?³n p??blica con las mejores condiciones posibles Para que nuestros mayores puedan disfrutar del f??tbol |\n| |\n.\nPrecios y Factura: ERROR DOC INTEL. \nTramitación: Ayuda Elypse\n===', '# 4 Tramitaci?³n  \n4 1 Tramitaci?³n TELCO\nNo aplica, ya que estos productos no est??n disponibles en Telco  \n4 2 Tramitaci?³n no TELCO\nNo aplica']]
------------------------
total number of chunks: 4

Any idea? Thanks!!!

**Comment by asevillano** [comment]
Hi Gioele, here you have the content in a .txt file.
[text.txt](https://github.com/user-attachments/files/15864662/text.txt)
thanks!
Angel

**Comment by gioelecrispo** [comment]
Hello @asevillano, 
the text you gave me is really noisy: it has a lot of weird characters (punctuation marks and notes - e.g.: "`Descripci?³no`") and `\n` that very likely make it difficult for the sentencizer (i.e. `stanza` library) to correctly detect sentences. 

As a consequence, the text parts we get from the sentencizer are the following:

1. **Tokens**: 72 - **Text**: 'Descripción: Ayuda Elypse\nApartados que cambian Descripci?³n del cambio Fecha entrada en vigor Fecha actualización del documento Lanzamiento promoci?³n 23/06/2020 24/06/2020\n1 1 ¿En qué consiste la promoción? '
2. **Tokens**: 446 - **Text**: 'La Liga y Mediapro han llegado a un acuerdo con los operadores para que puedan ofrecer el f??tbol gratis (Canal La Liga TV) en las residencias de ancianos Telef?³nica participa de este acuerdo dando a las residencias un producto con los mismos contenidos que el de BAR pero a un precio mucho m??s competitivo Al cliente le hablamos de un producto para residencias a un precio muy competitivo yÂ con el canal LaLiga TV gratis, no de una promoci?³n sobre el producto BAR A qui??n aplica: Residencias de ancianos (incluidas en el c?³didgo CNAE 8731 -asistencia en establecimientos residenciales para personas mayores-) que llamen para solicitar el f??tbol gratuito en sus residencias (zonas comunes y cafeter?\xada) Tambi??n para residencias que tengan el producto BAR instalado en la cafeter?\xada o zona com??n y soliciten el f??tbol gratis Cuando llame al 1004 o acuda a una tienda el responsable de una residencia de ancianos para solicitar el producto, derivar siempre la demanda a su comercial o al 900 26 22 62 El PVP del producto es de 112 â??/mes IVA incluido (pese a que el f??tbol -LIGA TV- es gratis, el producto tiene otros contenidos que s?\xad tienen un coste) hasta el 31 de agosto de 2020\nAsegura siempre\nInforma al cliente de que esta promoci?³n ser?? v??lida solo para residencias de ancianos; '
3. **Tokens**: 105 - **Text**: 'aquellas incluidas en el c?³digo CNAE 8731 Se har??n comprobaciones antes y despu??s de instalar el equipo\nContratación y disfrute\nFechas de contratación Fechas o periodo de disfrute Desde 23/06/2020 Hasta 31/08/2020 Hasta el 31 de agosto\n1 2 ¿A quién va dirigida? '
4. **Tokens**: 272 - **Text**: ('Residencias de ancianos Solo disponible en tecnolog?\xada 1P SAT Segmento del cliente: Autónomos Empresas\n1 3 Incompatibilidades\nNo aplica\n1 4 Canales de Venta\nOtros Instaladores DTS y Digitex\n1 5 Comunicación\nCampañas en Medios Otros soportes de comunicación N/A N/A\n1 6 Mantenimiento de la promoción\nNo aplica\n1 7 Compromiso de la promoci?³n y movimientos con penalizaci?³n\nNo aplica\n1 8 Hitos de la promoción (detallados)\nFecha Descripción 23/06/2020 Lanzamiento promoci?³n Residencias de ancianos 112 â??/mes hasta el 31 de agosto de 2020\n.\nArgumentación: Ayuda Elypse\n===\n2 Argumentaci?³n\nCLAIM COMERCIAL: Para clientes que soliciten el nuevo producto para residencias de ancianos Movistar es consciente de la situaci?³n que se ha generando y lo impactadas que se han visto las residencias de ancianos '
5. **Tokens**: 69 - **Text**: 'Por eso quiere ofrecer un producto de difusi?³n p??blica con las mejores condiciones posibles Para que nuestros mayores puedan disfrutar del f??tbol\n.\nPrecios y Factura: ERROR DOC INTEL. '
6. **Tokens**: 53 - **Text**: 'Tramitación: Ayuda Elypse\n===\n4 Tramitaci?³n\n4 1 Tramitaci?³n TELCO\nNo aplica, ya que estos productos no est??n disponibles en Telco '
7. **Tokens**: 16 - **Text**: '4 2 Tramitaci?³n no TELCO\nNo aplica '

You can see that **those are not actual sentences**, and the library is designed to work with small sentences, as we would do in reality.

Indeed, the aim of this library, chunkipy, is to split the text into **meaningful** chunks, having sentences that are not cut in the middle and preserving the semantic meaning of the chunk. Naturally, this make sense only if the text is clear enough to make it possible for the sentencizer to split the text into meaningful sentences.


Going back to the example, with your configuration, i.e. `TextChunker(512, tokens=True, overlap_percent=0.25, token_estimator=bert_token_estimator)`, the overlapping size is `512 * 0.25 = 128`, meaning that any text part that has more than 128 tokens is not used for the overlapping. This is also useful to avoid that multiple chunks contains the same information with no benefit. Again, the root cause is to be searched in the quality of the text which is noisy.

I would suggest you to work on cleaning your text before the use of chunkipy. This is a general rule/advice to have in mind when working with NLP and semantic algorithm and networks. Even if more powerful networks like GPT are more able to deal with grammar and syntax errors, they can struggle and make errors as well when the text is so noisy. 

--- 

Closing this issue as there is no bug with the overlapping.
